import type { WindowConfig } from './types'
import { WindowType } from '../types/window'

export const VOICE_IME_SIZE = {
  WIDTH: 280,
  HEIGHT: 120,
} as const

export const WINDOW_CONFIGS: Record<WindowType, WindowConfig> = {
  [WindowType.MAIN]: {
    width: 1440,
    height: 1080,
    position: 'center',
    title: 'Demo',
    frame: true,
    transparent: false,
    alwaysOnTop: false,
    skipTaskbar: false,
    resizable: true,
    movable: true,
    focusable: true,
    hasShadow: true,
    htmlPath: 'index.html',
    autoHideMenuBar: true,
    show: true,
    openDevTools: true,
  },

  [WindowType.VOICE_IME]: {
    width: VOICE_IME_SIZE.WIDTH,
    height: VOICE_IME_SIZE.HEIGHT,
    position: 'bottom-center',
    title: 'Voice IME',
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    skipTaskbar: true,
    resizable: false,
    movable: false,
    focusable: false,
    hasShadow: true,
    htmlPath: 'voice-ime.html',
    show: false,
    openDevTools: false,
  },

  [WindowType.OAUTH]: {
    width: 600,
    height: 750,
    position: 'center',
    title: 'OAuth Login',
    frame: true,
    transparent: false,
    modal: true,
    alwaysOnTop: false,
    movable: true,
    focusable: true,
    show: true,
    initialUrl: 'about:blank',
  },

  [WindowType.SELECTION]: {
    width: 500,
    height: 300,
    position: 'center',
    title: 'Selected Text',
    frame: false,
    transparent: false,
    alwaysOnTop: false,
    skipTaskbar: false,
    resizable: true,
    movable: true,
    focusable: true,
    hasShadow: true,
    htmlPath: 'selection.html',
    show: false,
    openDevTools: false,
    setAlwaysOnTopOnShow: true,
  },

  [WindowType.SHORTCUT_TEST]: {
    width: 400,
    height: 240,
    position: 'center',
    title: 'Shortcut Test',
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    skipTaskbar: true,
    resizable: false,
    movable: false,
    focusable: true,
    hasShadow: true,
    htmlPath: 'shortcut-test.html',
    show: false,
    openDevTools: false,
  },
}
