export { WINDOW_DATA_ATTR } from './dataAttributes'
export { mountTransparentWindow } from './mountTransparentWindow'
export { ResizeHandles } from './ResizeHandles'
export type { ResizeHandlesProps } from './ResizeHandles'
export { WINDOW_SURFACE_SHADOW } from './surfaceShadow'
export { useLogicalWindowRoute } from './useLogicalWindowRoute'
export { getElementWindowHitTestRegion, getInsetWindowHitTestRegion, getResizeHandleHitTestRegions, useRoundedWindowHitTest } from './useRoundedWindowHitTest'
export type { RoundedWindowHitTestOptions, RoundedWindowHitTestRegion, RoundedWindowHitTestRegionInput } from './useRoundedWindowHitTest'
export type { WindowDragOptions } from './useWindowDrag'
export { useWindowDrag } from './useWindowDrag'

export { useWindowResize } from './useWindowResize'
export type { ResizeDir, UseWindowResizeOptions, UseWindowResizeReturn } from './useWindowResize'
